python:
  - "2.7"

services:
  - mysql
  - sqlite3

env:
  - TARGET_DATABASES=MySQL DB_TYPE=MySQL MYSQL_HOST="127.0.0.1" MYSQL_PORT=3306 MYSQL_USER=root MYSQL_PASSWORD="" MYSQL_DB=testing
  - TARGET_DATABASES=SQLite3 DB_TYPE=SQLite3 SQLITE3_PATH=":memory:"

install: sudo make reqs

before_script:
  - sh -c "if [ $DB_TYPE = 'MySQL' ] ; then mysql -e 'create database IF NOT EXISTS testing;' ; fi"

script: make test
